SEED: 223

DATASET:
  datadir: /root/datasets
  num_samples_per_class: 128

OPTIMIZER:
  opt_name: SGD
  # opt_name: AdamW
  params:
    lr: 0.03
    weight_decay: 0.0001
    momentum: 0.9

TRAINING:
  # batch_size: 128
  batch_size: 16
  test_batch_size: 128
  epochs: 50
  log_interval: 1
  use_scheduler: true
  use_wandb: false
  # best temp: 
  temperature: 20
  alpha: 0.5
  split_ratio: 1

ATTENTION_VISUALIZATION:
  save_interval: 10
  max_samples_per_batch: 4
  image_size: 224
  patch_size: 16

RESULT:
  savedir: './saved_model'